import Head from 'next/head'
import Top from '@/pages/components/Top'
import style from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>TUYU FunSite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.wrap}>
        <Top />
      </div>
    </>
  )
}
